import type { CameraObjectProps } from "../../../core/types";

export function getCameraObjectPropsSignature(
  camera: CameraObjectProps | null,
): string {
  if (!camera) return "none";
  return [
    camera.live,
    camera.position.x,
    camera.position.y,
    camera.position.z,
    camera.rotation.x,
    camera.rotation.y,
    camera.rotation.z,
    camera.fov,
    camera.near,
    camera.far,
    camera.sensor.width,
    camera.sensor.height,
    camera.dof.enabled,
    camera.dof.debug,
    camera.dof.blurMode,
    camera.dof.focusDistance,
    camera.dof.fNumber,
    camera.dof.maxBlurPx,
    camera.dof.bokeh.preset,
    camera.autoFocus.enabled,
    camera.autoFocus.targetId ?? "",
    camera.autoFocus.zOffset,
    camera.autoFocus.rackFocus,
    camera.autoFocus.duration,
    camera.autoFocus.ease,
    camera.autoOrient,
    camera.lockTarget.targetId ?? "",
    camera.lockTarget.offset.x,
    camera.lockTarget.offset.y,
    camera.lockTarget.offset.z,
    camera.lens.distortion.enabled,
    camera.lens.distortion.amount,
    camera.lens.chromaticAberration.enabled,
    camera.lens.chromaticAberration.amountPx,
    camera.lens.vignette.enabled,
    camera.lens.vignette.amount,
    camera.lens.vignette.feather,
    camera.post.exposure.enabled,
    camera.post.exposure.ev,
    camera.post.tonemap.enabled,
    camera.post.tonemap.mode,
    camera.post.grade.enabled,
    camera.post.grade.lift,
    camera.post.grade.gamma,
    camera.post.grade.gain,
    camera.post.grain.enabled,
    camera.post.grain.amount,
    camera.post.grain.size,
  ].join(":");
}
