import type { MouseEvent as ReactMouseEvent, RefObject } from "react";
import type { AdjustmentLayerSelection, CompositionSelection, MotionMarkerSelection, TimelineBlankContextTarget, TimelineNodeContextTarget } from "../../app/types";
import type { TimelineMarkerMove, TimelineMarkerResize } from "../../core/timeline";
import type { AdjustmentEffectId, AdjustmentLayer, BackgroundLayer, FrameObject, MotionEffectId, MotionEffectKind, MotionTrack, Part, TimelineLayerState, TimelineMode, TimelineMotionLayerKind, TimelinePart, TimelineViewportState, TranslationMarker, ZoomMarker } from "../../core/types";

export type TimelinePanelProps = {
  timelineName: string;
  timeline: TimelinePart[];
  motionMarkers: Part["motionMarkers"];
  timelineLayers: TimelineLayerState;
  adjustmentLayers: AdjustmentLayer[];
  timelineViewportState: TimelineViewportState;
  mode: TimelineMode;
  selectedPartId: string;
  selectedParts: CompositionSelection[];
  selectedMotionMarkerPartId: string | null;
  selectedMotionMarkerId: string | null;
  selectedMotionMarkers: MotionMarkerSelection[];
  selectedAdjustmentLayerId: string | null;
  selectedAdjustmentLayers: AdjustmentLayerSelection[];
  sceneDuration: number;
  currentSceneTime: number;
  isPlaying: boolean;
  playbackPlayheadRef: RefObject<HTMLDivElement | null>;
  scrubbingRef: RefObject<boolean>;
  fastSelectEnabled: boolean;
  scrubCommitThrottleMs: number;
  defaultNewMarkerDurationSeconds: number;
  timelineEndPaddingFraction: number;
  scrubSnapEnabled: boolean;
  onScrub: (time: number) => void;
  onScrubStart: () => void;
  onScrubEnd: () => void;
  onModeChange: (mode: TimelineMode) => void;
  onTimelineViewportStateChange: (updater: (state: TimelineViewportState) => TimelineViewportState) => void;
  onTimelineLayersChange: (updater: (state: TimelineLayerState) => TimelineLayerState, options?: { history?: boolean }) => void;
  onAddCompositionLayer: (targetLayerId?: string, placement?: "before" | "after") => void;
  onRemoveCompositionLayer: (layerId: string) => void;
  onAddAdjustmentLayer: (targetLayerId?: string, placement?: "before" | "after") => void;
  onRemoveAdjustmentLayer: (layerId: string) => void;
  onAddMotionLayer: (kind?: TimelineMotionLayerKind, targetLayerId?: string, placement?: "before" | "after") => void;
  onRemoveMotionLayer: (layerId: string) => void;
  onSelectPart: (id: string) => void;
  onOpenComposePart: (id: string) => void;
  onSelectMotionMarker: (partId: string, markerId: string) => void;
  onSelectMotionMarkers: (selection: MotionMarkerSelection[]) => void;
  onSelectAdjustmentLayer: (layerId: string) => void;
  onSelectAdjustmentLayers: (selection: AdjustmentLayerSelection[]) => void;
  onSelectTimelineNodes: (selection: { adjustmentLayers: AdjustmentLayerSelection[]; compositions: CompositionSelection[]; motionMarkers: MotionMarkerSelection[] }) => void;
  onClearTimelineSelection: () => void;
  onOpenNodeContextMenu: (event: ReactMouseEvent<HTMLElement>, target: TimelineNodeContextTarget) => void;
  onOpenBlankContextMenu: (event: ReactMouseEvent<HTMLElement>, target: TimelineBlankContextTarget) => void;
  onMoveAdjustmentLayer: (layerId: string, start: number, targetLayerId?: string) => void;
  onUpdateAdjustmentLayer: (layerId: string, updater: (layer: AdjustmentLayer) => AdjustmentLayer) => void;
  onReorderPart: (sourcePartId: string, targetPartId: string) => void;
  onMoveComposition: (compositionId: string, start: number, targetLayerId?: string) => void;
  onMoveCompositions: (moves: Array<{ compositionId: string; start: number; targetLayerId?: string }>) => void;
  onUpdateComposition: (compositionId: string, updater: (composition: Part) => Part) => void;
  onMoveZoomMarker: (sourcePartId: string, markerId: string, targetPartId: string, start: number, targetLayerId?: string) => void;
  onMoveZoomMarkers: (moves: TimelineMarkerMove[]) => void;
  onMoveTranslationMarker: (sourcePartId: string, markerId: string, targetPartId: string, start: number, targetLayerId?: string) => void;
  onMoveTranslationMarkers: (moves: TimelineMarkerMove[]) => void;
  onUpdateZoomMarkers: (partId: string, updater: (markers: ZoomMarker[], part: Part) => ZoomMarker[]) => void;
  onUpdateTranslationMarkers: (partId: string, updater: (markers: TranslationMarker[], part: Part) => TranslationMarker[]) => void;
  onResizeZoomMarkers: (resizes: TimelineMarkerResize[]) => void;
  onResizeTranslationMarkers: (resizes: TimelineMarkerResize[]) => void;
  onAddComposition: (compositionId: string, targetLayerId?: string, start?: number) => void;
  onAddAdjustmentEffect: (effectId: AdjustmentEffectId, sceneTime: number, layerId?: string) => void;
  onAddMotionEffect: (effectId: MotionEffectId, layerId: string, sceneTime: number) => void;
  composeAnimationPart?: Part | null;
  selectedObjectIds?: string[];
  onExitCompose?: () => void;
  onSelectComposeObjects?: (objects: FrameObject[]) => void;
  onRenameComposeAnimationLayer?: (layerId: string, name: string) => void;
  onUpdateComposeBackgroundMotion?: (updater: (motion: MotionTrack | undefined, background: BackgroundLayer) => MotionTrack | undefined) => void;
  onUpdateComposeObjectMotion?: (objectId: string, updater: (motion: MotionTrack | undefined, object: FrameObject) => MotionTrack | undefined) => void;
  onUpdateComposeBackgroundAnimation?: (updater: (animations: import("../../core/types").LayerAnimation[]) => import("../../core/types").LayerAnimation[]) => void;
  onUpdateComposeObjectAnimation?: (objectId: string, updater: (animations: import("../../core/types").LayerAnimation[]) => import("../../core/types").LayerAnimation[]) => void;
};

export type EffectDragPreview = {
  category: "adjustment" | "motion" | "composition";
  effectId?: string;
  isEmpty?: boolean;
  kind?: MotionEffectKind;
  layerKey: string;
  label?: string;
  sourceMissing?: boolean;
  start: number;
  duration: number;
  initialClientX: number;
  initialStart: number;
};

export type AbsoluteTimelineMarker<T extends { id: string; start: number; duration: number }> = T & {
  sourcePartId: string;
  sourcePartStart: number;
};

export type TimelinePartMotionView = TimelinePart & {
  zoomMarkers: ZoomMarker[];
  translationMarkers: TranslationMarker[];
};
