import { useMemo } from "react";
import type { PlaybackBarProps } from "../../shell/PlaybackBar";

type Omitted = Omit<PlaybackBarProps, "previewColumnHovered">;

export function usePlaybackBarProps(input: Omitted): Omitted {
  const {
    fastSelectEnabled,
    framePreviewScale,
    frameZoomBarOpen,
    frameZoomControlRef,
    isPlaying,
    playbackBorderScrubberRef,
    playbackDisplayDuration,
    playbackTimeLabelRef,
    scrubSnapEnabled,
    formatPlaybackTimeLabel,
    toPlaybackDisplayTime,
    jumpToEnd,
    jumpToNextPart,
    jumpToStart,
    pausePlaybackAtCurrentTime,
    pausePlaybackForTimelineScrub,
    resumePlaybackAfterTimelineScrub,
    scrubToPlaybackDisplayTime,
    setFastSelectEnabled,
    setScrubSnapEnabled,
    stepSceneTime,
    toggleFrameZoomBar,
    togglePlayback,
    updateFramePreviewScale,
  } = input;

  return useMemo<Omitted>(
    () => ({
      fastSelectEnabled,
      framePreviewScale,
      frameZoomBarOpen,
      frameZoomControlRef,
      isPlaying,
      playbackBorderScrubberRef,
      playbackDisplayDuration,
      playbackTimeLabelRef,
      scrubSnapEnabled,
      formatPlaybackTimeLabel,
      toPlaybackDisplayTime,
      jumpToEnd,
      jumpToNextPart,
      jumpToStart,
      pausePlaybackAtCurrentTime,
      pausePlaybackForTimelineScrub,
      resumePlaybackAfterTimelineScrub,
      scrubToPlaybackDisplayTime,
      setFastSelectEnabled,
      setScrubSnapEnabled,
      stepSceneTime,
      toggleFrameZoomBar,
      togglePlayback,
      updateFramePreviewScale,
    }),
    [
      fastSelectEnabled,
      framePreviewScale,
      frameZoomBarOpen,
      frameZoomControlRef,
      isPlaying,
      playbackBorderScrubberRef,
      playbackDisplayDuration,
      playbackTimeLabelRef,
      scrubSnapEnabled,
      formatPlaybackTimeLabel,
      toPlaybackDisplayTime,
      jumpToEnd,
      jumpToNextPart,
      jumpToStart,
      pausePlaybackAtCurrentTime,
      pausePlaybackForTimelineScrub,
      resumePlaybackAfterTimelineScrub,
      scrubToPlaybackDisplayTime,
      setFastSelectEnabled,
      setScrubSnapEnabled,
      stepSceneTime,
      toggleFrameZoomBar,
      togglePlayback,
      updateFramePreviewScale,
    ],
  );
}
