import type { ProjectManifest } from "./core/types";

export const sampleProject: ProjectManifest = {
  id: "prj_v01_sample",
  name: "Agentic Motion Primer",
  resolution: { width: 1920, height: 1080 },
  assetsPath: "clipper/projects/prj_v01_sample/assets",
  assets: [
    { id: "ast_folder_media", name: "media", kind: "folder", children: [{ id: "ast_grid_ref", name: "grid-reference.png", kind: "file", path: "clipper/projects/prj_v01_sample/assets/media/grid-reference.png" }] },
    { id: "ast_folder_audio", name: "audio", kind: "folder", children: [] },
    { id: "ast_brand", name: "brand-palette.json", kind: "file", path: "clipper/projects/prj_v01_sample/assets/brand-palette.json" },
  ],
  scenes: [
    {
      id: "scn_opening",
      name: "Opening Sequence",
      parts: [
        {
          id: "prt_grid_reveal",
          name: "Grid Reveal",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_grid_reveal.ts",
          duration: 7,
          frame: { width: 1920, height: 1080, style: { background: "#050505" } },
          background: { id: "background", name: "Background", style: { background: "#050505" }, elements: [] },
          snapshot: [
            { at: "00:01", description: "Off-white drafting lines establish the fixed 1920x1080 frame." },
            { at: "00:04", description: "The title block slides into the left third while metadata cards queue up." },
            { at: "00:07", description: "Ending with the hero object ready for a shared-id pan." },
          ],
          zoomMarkers: [
            { id: "zom_title", start: 2.2, duration: 2.4, focus: { x: 580, y: 438 }, scale: 1.5 },
          ],
          translationMarkers: [],
          objects: [
            {
              id: "hero-title",
              name: "Hero Title",
              type: "text",
              selector: "[data-object-id='hero-title']",
              bounds: { x: 180, y: 292, width: 820, height: 190 },
              content: "Typescript\nBecomes Video",
              style: { color: "#ffffff", fontSize: 86, fontWeight: 760, lineHeight: 0.95, letterSpacing: -4 },
              motion: { y: [46, 0], opacity: [0, 1], duration: 0.9, ease: "easeOut" },
            },
            {
              id: "hero-panel",
              name: "Hero Panel",
              type: "rect",
              selector: "[data-object-id='hero-panel']",
              bounds: { x: 1240, y: 190, width: 430, height: 570 },
              style: { background: "var(--clipper-accent)", borderRadius: 34, boxShadow: "0 28px 80px rgb(var(--clipper-accent-rgb) / 0.24)" },
              motion: { y: [-72, 0], rotate: [-3, 0], delay: 0.45, duration: 1.25, ease: "circOut" },
            },
            {
              id: "object-rule",
              name: "Typewriter Subtitle",
              type: "text",
              selector: "[data-object-id='object-rule']",
              bounds: { x: 190, y: 762, width: 920, height: 86 },
              content: "Every visible mark becomes editable motion code.",
              style: { color: "#aeb8c2", fontSize: 30, lineHeight: 1.2, letterSpacing: -0.4 },
              motion: { opacity: [0, 1], duration: 2.1, delay: 1.15, ease: "linear" },
            },
          ],
        },
        {
          id: "prt_blank_pause",
          name: "Black Pause",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_blank_pause.ts",
          duration: 3,
          frame: { width: 1920, height: 1080, style: { background: "#000000" } },
          background: { id: "background", name: "Background", style: { background: "#000000" }, elements: [] },
          snapshot: [{ at: "00:03", description: "A quiet black empty composition keeps the linear timeline readable." }],
          zoomMarkers: [],
          translationMarkers: [],
          objects: [],
        },
        {
          id: "prt_animated_dot",
          name: "Animated Dot Template",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_animated_dot.ts",
          duration: 5,
          frame: { width: 1920, height: 1080, style: { background: "#06070b" } },
          background: {
            id: "background",
            name: "Animated Dot Background",
            style: {
              background: "#06070b",
            },
            stretchToElements: true,
            elements: [
              {
                id: "const-dot-field",
                name: "Constant Dot Field",
                type: "rect",
                selector: "[data-object-id='const-dot-field']",
                bounds: { x: -1100, y: -600, width: 4200, height: 2280 },
                style: {
                  backgroundImage: "radial-gradient(circle, rgb(var(--clipper-accent-rgb) / 0.68) 0 3px, transparent 4px)",
                  backgroundSize: "96px 96px",
                  opacity: 0.45,
                },
                motion: { x: [-96, 0], y: [-96, 0], duration: 5, ease: "linear", loop: true },
              },
              {
                id: "hero-dot",
                name: "Animated Hero Dot",
                type: "rect",
                selector: "[data-object-id='hero-dot']",
                bounds: { x: 860, y: 460, width: 200, height: 200 },
                style: { background: "var(--clipper-accent)", borderRadius: 999, boxShadow: "0 0 90px rgb(var(--clipper-accent-rgb) / 0.55)" },
                motion: { x: [-220, 220], y: [120, -80], duration: 5, ease: "easeInOut", loop: true },
              },
            ],
          },
          snapshot: [
            { at: "00:01", description: "A separate background layer renders behind the frame objects." },
            { at: "00:05", description: "The dot motion is code-authored on the background layer." },
          ],
          zoomMarkers: [],
          translationMarkers: [],
          objects: [],
        },
        {
          id: "prt_editor_surface",
          name: "Editor Surface",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_editor_surface.ts",
          duration: 8,
          frame: { width: 1920, height: 1080, style: { background: "#050505" } },
          background: { id: "background", name: "Background", style: { background: "#050505" }, elements: [] },
          snapshot: [
            { at: "00:02", description: "The shared hero-title id pans into an editor annotation." },
            { at: "00:05", description: "Inspector and screenshot selector metadata are emphasized." },
            { at: "00:08", description: "Ending with zoom row and main timeline aligned." },
          ],
          zoomMarkers: [
            { id: "zom_inspector", start: 3.4, duration: 2.8, focus: { x: 1540, y: 430 }, scale: 1.8 },
          ],
          translationMarkers: [],
          objects: [
            {
              id: "hero-title",
              name: "Hero Title Continuity",
              type: "text",
              selector: "[data-object-id='hero-title']",
              bounds: { x: 120, y: 130, width: 650, height: 110 },
              content: "Shared IDs unlock hero pans",
              style: { color: "#ffffff", fontSize: 48, fontWeight: 720, letterSpacing: -1.5 },
              layoutId: "hero-title",
              motion: { opacity: [0, 1], duration: 0.7, ease: "easeInOut" },
            },
            {
              id: "inspector-card",
              name: "Inspector Card",
              type: "rect",
              selector: "[data-object-id='inspector-card']",
              bounds: { x: 1290, y: 210, width: 420, height: 520 },
              style: { background: "#111820", border: "2px solid var(--clipper-accent)", borderRadius: 26 },
              motion: { opacity: [0, 1], x: [60, 0], duration: 0.6, ease: "easeOut" },
            },
            {
              id: "selector-box-demo",
              name: "Screenshot Selector Demo",
              type: "rect",
              selector: "[data-object-id='selector-box-demo']",
              bounds: { x: 350, y: 430, width: 690, height: 330 },
              style: { background: "rgb(var(--clipper-accent-rgb) / 0.12)", border: "3px dashed var(--clipper-accent)", borderRadius: 8 },
              motion: { opacity: [0, 1], duration: 1, ease: "linear" },
            },
          ],
        },
      ],
    },
  ],
};
