import type { ProjectManifest } from "./core/types";

export const sampleProject: ProjectManifest = {
  id: "prj_v01_sample",
  name: "Agentic Motion Primer",
  resolution: { width: 1920, height: 1080 },
  assetsPath: "clipper/projects/prj_v01_sample/assets",
  assets: [
    { id: "ast_folder_media", name: "media", kind: "folder", children: [{ id: "ast_grid_ref", name: "grid-reference.png", kind: "file", path: "clipper/projects/prj_v01_sample/assets/media/grid-reference.png" }] },
    { id: "ast_folder_audio", name: "audio", kind: "folder", children: [] },
    { id: "ast_brand", name: "brand-palette.json", kind: "file", path: "clipper/projects/prj_v01_sample/assets/brand-palette.json" },
  ],
  scenes: [
    {
      id: "scn_opening",
      name: "Opening Sequence",
      parts: [
        {
          id: "prt_grid_reveal",
          name: "Grid Reveal",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_grid_reveal.ts",
          duration: 7,
          frame: { width: 1920, height: 1080, style: { background: "#050505" } },
          background: { id: "background", name: "Background", style: { background: "#050505" }, elements: [] },
          snapshot: [
            { at: "00:01", description: "Off-white drafting lines establish the fixed 1920x1080 frame." },
            { at: "00:04", description: "The title block slides into the left third while metadata cards queue up." },
            { at: "00:07", description: "Ending with the hero object ready for a shared-id pan." },
          ],
          zoomMarkers: [
            { id: "zom_title", start: 2.2, duration: 2.4, focus: { x: 580, y: 438 }, scale: 1.5 },
          ],
          translationMarkers: [],
          objects: [
            {
              id: "hero-title",
              name: "Hero Title",
              type: "text",
              selector: "[data-object-id='hero-title']",
              bounds: { x: 180, y: 292, width: 820, height: 190 },
              content: "Typescript\nBecomes Video",
              style: { color: "#ffffff", fontSize: 86, fontWeight: 760, lineHeight: 0.95, letterSpacing: -4 },
              motion: { y: [46, 0], opacity: [0, 1], duration: 0.9, ease: "easeOut" },
            },
            {
              id: "hero-panel",
              name: "Hero Panel",
              type: "rect",
              selector: "[data-object-id='hero-panel']",
              bounds: { x: 1240, y: 190, width: 430, height: 570 },
              style: { background: "var(--clipper-accent)", borderRadius: 34, boxShadow: "0 28px 80px rgb(var(--clipper-accent-rgb) / 0.24)" },
              motion: { y: [-72, 0], rotate: [-3, 0], delay: 0.45, duration: 1.25, ease: "circOut" },
            },
            {
              id: "object-rule",
              name: "Typewriter Subtitle",
              type: "text",
              selector: "[data-object-id='object-rule']",
              bounds: { x: 190, y: 762, width: 920, height: 86 },
              content: "Every visible mark becomes editable motion code.",
              style: { color: "#aeb8c2", fontSize: 30, lineHeight: 1.2, letterSpacing: -0.4 },
              motion: { opacity: [0, 1], duration: 2.1, delay: 1.15, ease: "linear" },
            },
          ],
        },
        {
          id: "prt_blank_pause",
          name: "Black Pause",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_blank_pause.ts",
          duration: 3,
          frame: { width: 1920, height: 1080, style: { background: "#000000" } },
          background: { id: "background", name: "Background", style: { background: "#000000" }, elements: [] },
          snapshot: [{ at: "00:03", description: "A quiet black empty composition keeps the linear timeline readable." }],
          zoomMarkers: [],
          translationMarkers: [],
          objects: [],
        },
        {
          id: "prt_animated_dot",
          name: "Animated Dot Template",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_animated_dot.ts",
          duration: 5,
          frame: { width: 1920, height: 1080, style: { background: "#06070b" } },
          background: {
            id: "background",
            name: "Animated Dot Background",
            style: {
              background: "#06070b",
            },
            stretchToElements: true,
            elements: [
              {
                id: "const-dot-field",
                name: "Constant Dot Field",
                type: "rect",
                selector: "[data-object-id='const-dot-field']",
                bounds: { x: -1100, y: -600, width: 4200, height: 2280 },
                style: {
                  backgroundImage: "radial-gradient(circle, rgb(var(--clipper-accent-rgb) / 0.68) 0 3px, transparent 4px)",
                  backgroundSize: "96px 96px",
                  opacity: 0.45,
                },
                motion: { x: [-96, 0], y: [-96, 0], duration: 5, ease: "linear", loop: true },
              },
              {
                id: "hero-dot",
                name: "Animated Hero Dot",
                type: "rect",
                selector: "[data-object-id='hero-dot']",
                bounds: { x: 860, y: 460, width: 200, height: 200 },
                style: { background: "var(--clipper-accent)", borderRadius: 999, boxShadow: "0 0 90px rgb(var(--clipper-accent-rgb) / 0.55)" },
                motion: { x: [-220, 220], y: [120, -80], duration: 5, ease: "easeInOut", loop: true },
              },
            ],
          },
          snapshot: [
            { at: "00:01", description: "A separate background layer renders behind the frame objects." },
            { at: "00:05", description: "The dot motion is code-authored on the background layer." },
          ],
          zoomMarkers: [],
          translationMarkers: [],
          objects: [],
        },
        {
          id: "prt_animated_graph",
          name: "Animated Graph Reveal",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_animated_graph.ts",
          duration: 8,
          frame: { width: 1920, height: 1080, style: { background: "#071018" } },
          background: {
            id: "background",
            name: "Animated Graph Background",
            style: { background: "radial-gradient(circle at 72% 24%, rgba(90,214,255,0.18), transparent 34%), linear-gradient(135deg, #071018 0%, #0c1724 56%, #05070c 100%)" },
            elements: [
              {
                id: "graph-grid-field",
                name: "Soft Graph Grid",
                type: "rect",
                selector: "[data-object-id='graph-grid-field']",
                bounds: { x: 220, y: 190, width: 1180, height: 690 },
                style: {
                  backgroundImage: "linear-gradient(rgba(255,255,255,0.055) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.055) 1px, transparent 1px)",
                  backgroundSize: "118px 86px",
                  opacity: 0.62,
                  borderRadius: 32,
                },
                motion: { opacity: [0, 0.62], duration: 1.1, delay: 0.1, ease: "easeOut" },
              },
            ],
          },
          snapshot: [
            { at: "00:01", description: "The graph card, grid, axes, tick labels, and title reveal in layers." },
            { at: "00:04", description: "The cyan line draws across the quarters while endpoint markers pop on." },
            { at: "00:08", description: "The right-side value card finishes ticking to match the final line position." },
          ],
          zoomMarkers: [{ id: "zom_graph_values", start: 4.8, duration: 2, focus: { x: 1598, y: 486 }, scale: 1.45 }],
          translationMarkers: [],
          objects: [
            { id: "graph-title", name: "Graph Title", type: "text", selector: "[data-object-id='graph-title']", bounds: { x: 220, y: 94, width: 760, height: 82 }, content: "Revenue velocity", style: { color: "#f7fbff", fontSize: 58, fontWeight: 760, letterSpacing: -2.2, lineHeight: 1 }, motion: { y: [28, 0], opacity: [0, 1], duration: 0.85, ease: "easeOut" } },
            { id: "graph-subtitle", name: "Graph Subtitle", type: "text", selector: "[data-object-id='graph-subtitle']", bounds: { x: 224, y: 164, width: 780, height: 44 }, content: "Axes reveal first. Lines draw second. Live values count with the stroke.", style: { color: "rgba(218,233,246,0.68)", fontSize: 24, fontWeight: 500, letterSpacing: -0.3 }, motion: { y: [16, 0], opacity: [0, 1], duration: 0.8, delay: 0.28, ease: "easeOut" } },
            { id: "graph-y-axis", name: "Y Axis", type: "rect", selector: "[data-object-id='graph-y-axis']", bounds: { x: 300, y: 238, width: 4, height: 620 }, style: { background: "rgba(231,244,255,0.86)", borderRadius: 999, transformOrigin: "bottom center" }, motion: { y: [70, 0], opacity: [0, 1], duration: 0.7, delay: 0.45, ease: "easeOut" } },
            { id: "graph-x-axis", name: "X Axis", type: "rect", selector: "[data-object-id='graph-x-axis']", bounds: { x: 300, y: 854, width: 1110, height: 4 }, style: { background: "rgba(231,244,255,0.86)", borderRadius: 999, transformOrigin: "left center" }, motion: { x: [-70, 0], opacity: [0, 1], duration: 0.75, delay: 0.62, ease: "easeOut" } },
            { id: "graph-y-tick-1", name: "Y Tick 24k", type: "text", selector: "[data-object-id='graph-y-tick-1']", bounds: { x: 220, y: 726, width: 60, height: 32 }, content: "24k", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, textAlign: "right", fontWeight: 650 }, motion: { x: [-18, 0], opacity: [0, 1], duration: 0.45, delay: 0.95, ease: "easeOut" } },
            { id: "graph-y-tick-2", name: "Y Tick 48k", type: "text", selector: "[data-object-id='graph-y-tick-2']", bounds: { x: 220, y: 554, width: 60, height: 32 }, content: "48k", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, textAlign: "right", fontWeight: 650 }, motion: { x: [-18, 0], opacity: [0, 1], duration: 0.45, delay: 1.05, ease: "easeOut" } },
            { id: "graph-y-tick-3", name: "Y Tick 72k", type: "text", selector: "[data-object-id='graph-y-tick-3']", bounds: { x: 220, y: 382, width: 60, height: 32 }, content: "72k", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, textAlign: "right", fontWeight: 650 }, motion: { x: [-18, 0], opacity: [0, 1], duration: 0.45, delay: 1.15, ease: "easeOut" } },
            { id: "graph-x-tick-1", name: "X Tick Q1", type: "text", selector: "[data-object-id='graph-x-tick-1']", bounds: { x: 384, y: 884, width: 58, height: 30 }, content: "Q1", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, fontWeight: 650, textAlign: "center" }, motion: { y: [18, 0], opacity: [0, 1], duration: 0.42, delay: 1.05, ease: "easeOut" } },
            { id: "graph-x-tick-2", name: "X Tick Q2", type: "text", selector: "[data-object-id='graph-x-tick-2']", bounds: { x: 646, y: 884, width: 58, height: 30 }, content: "Q2", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, fontWeight: 650, textAlign: "center" }, motion: { y: [18, 0], opacity: [0, 1], duration: 0.42, delay: 1.15, ease: "easeOut" } },
            { id: "graph-x-tick-3", name: "X Tick Q3", type: "text", selector: "[data-object-id='graph-x-tick-3']", bounds: { x: 908, y: 884, width: 58, height: 30 }, content: "Q3", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, fontWeight: 650, textAlign: "center" }, motion: { y: [18, 0], opacity: [0, 1], duration: 0.42, delay: 1.25, ease: "easeOut" } },
            { id: "graph-x-tick-4", name: "X Tick Q4", type: "text", selector: "[data-object-id='graph-x-tick-4']", bounds: { x: 1170, y: 884, width: 58, height: 30 }, content: "Q4", style: { color: "rgba(218,233,246,0.62)", fontSize: 20, fontWeight: 650, textAlign: "center" }, motion: { y: [18, 0], opacity: [0, 1], duration: 0.42, delay: 1.35, ease: "easeOut" } },
            { id: "graph-line-1", name: "Graph Line Segment 1", type: "rect", selector: "[data-object-id='graph-line-1']", bounds: { x: 390, y: 718, width: 302, height: 10 }, style: { background: "#5ad6ff", borderRadius: 999, boxShadow: "0 0 28px rgba(90,214,255,0.52)", transformOrigin: "left center" } },
            { id: "graph-line-2", name: "Graph Line Segment 2", type: "rect", selector: "[data-object-id='graph-line-2']", bounds: { x: 674, y: 596, width: 296, height: 10 }, style: { background: "#5ad6ff", borderRadius: 999, boxShadow: "0 0 28px rgba(90,214,255,0.52)", transformOrigin: "left center" } },
            { id: "graph-line-3", name: "Graph Line Segment 3", type: "rect", selector: "[data-object-id='graph-line-3']", bounds: { x: 948, y: 450, width: 326, height: 10 }, style: { background: "#5ad6ff", borderRadius: 999, boxShadow: "0 0 28px rgba(90,214,255,0.52)", transformOrigin: "left center" } },
            { id: "graph-point-1", name: "Graph Endpoint Q1", type: "rect", selector: "[data-object-id='graph-point-1']", bounds: { x: 377, y: 710, width: 28, height: 28 }, style: { background: "#071018", border: "7px solid #5ad6ff", borderRadius: 999, boxShadow: "0 0 34px rgba(90,214,255,0.68)" }, motion: { opacity: [0, 1], duration: 0.24, delay: 1.66, ease: "easeOut" } },
            { id: "graph-point-2", name: "Graph Endpoint Q2", type: "rect", selector: "[data-object-id='graph-point-2']", bounds: { x: 637, y: 586, width: 28, height: 28 }, style: { background: "#071018", border: "7px solid #5ad6ff", borderRadius: 999, boxShadow: "0 0 34px rgba(90,214,255,0.68)" }, motion: { opacity: [0, 1], duration: 0.24, delay: 2.54, ease: "easeOut" } },
            { id: "graph-point-3", name: "Graph Endpoint Q3", type: "rect", selector: "[data-object-id='graph-point-3']", bounds: { x: 913, y: 440, width: 28, height: 28 }, style: { background: "#071018", border: "7px solid #5ad6ff", borderRadius: 999, boxShadow: "0 0 34px rgba(90,214,255,0.68)" }, motion: { opacity: [0, 1], duration: 0.24, delay: 3.42, ease: "easeOut" } },
            { id: "graph-point-4", name: "Graph Endpoint Q4", type: "rect", selector: "[data-object-id='graph-point-4']", bounds: { x: 1198, y: 326, width: 34, height: 34 }, style: { background: "#071018", border: "8px solid #5ad6ff", borderRadius: 999, boxShadow: "0 0 48px rgba(90,214,255,0.82)" }, motion: { opacity: [0, 1], duration: 0.28, delay: 4.3, ease: "easeOut" } },
            { id: "graph-value-card", name: "Value Card", type: "rect", selector: "[data-object-id='graph-value-card']", bounds: { x: 1466, y: 274, width: 262, height: 430 }, style: { background: "rgba(9,18,30,0.78)", border: "1px solid rgba(176,225,255,0.24)", borderRadius: 34, boxShadow: "0 28px 90px rgba(0,0,0,0.36)", backdropFilter: "blur(18px)" }, motion: { x: [48, 0], opacity: [0, 1], duration: 0.7, delay: 1.2, ease: "easeOut" } },
            { id: "graph-value-label", name: "Value Label", type: "text", selector: "[data-object-id='graph-value-label']", bounds: { x: 1502, y: 318, width: 190, height: 34 }, content: "LIVE ARR", style: { color: "rgba(218,233,246,0.58)", fontSize: 18, fontWeight: 800, letterSpacing: 2.8 }, motion: { opacity: [0, 1], duration: 0.4, delay: 1.45, ease: "easeOut" } },
            { id: "graph-value-primary", name: "Primary Ticking Value", type: "text", selector: "[data-object-id='graph-value-primary']", bounds: { x: 1498, y: 354, width: 200, height: 78 }, content: "$0k", style: { color: "#ffffff", fontSize: 58, fontWeight: 820, letterSpacing: -2.4, lineHeight: 1 } },
            { id: "graph-value-secondary", name: "Secondary Ticking Value", type: "text", selector: "[data-object-id='graph-value-secondary']", bounds: { x: 1502, y: 462, width: 190, height: 54 }, content: "+0%", style: { color: "#72f0b3", fontSize: 38, fontWeight: 780, letterSpacing: -1.2, lineHeight: 1 } },
            { id: "graph-value-caption", name: "Value Caption", type: "text", selector: "[data-object-id='graph-value-caption']", bounds: { x: 1504, y: 574, width: 172, height: 74 }, content: "Numbers tick in sync with line progress.", style: { color: "rgba(218,233,246,0.62)", fontSize: 22, lineHeight: 1.16, fontWeight: 540, letterSpacing: -0.3 }, motion: { y: [18, 0], opacity: [0, 1], duration: 0.55, delay: 2.1, ease: "easeOut" } },
          ],
        },
        {
          id: "prt_chart_showcase",
          name: "Chart Template Showcase",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_chart_showcase.ts",
          duration: 12,
          frame: { width: 1920, height: 1080, style: { background: "#06111c" } },
          background: {
            id: "background",
            name: "Chart Showcase Background",
            style: { background: "radial-gradient(circle at 12% 18%, rgba(114,240,179,0.16), transparent 28%), radial-gradient(circle at 82% 12%, rgba(90,214,255,0.18), transparent 34%), linear-gradient(135deg, #06111c 0%, #10182a 52%, #05070c 100%)" },
            elements: [],
          },
          snapshot: [
            { at: "00:02", description: "A gallery of defineChart templates reveals as editable chart cards." },
            { at: "00:06", description: "Cartesian, polar, categorical, and KPI-style chart families are represented." },
            { at: "00:12", description: "Use the code pane to copy any defineChart block into a new composition." },
          ],
          zoomMarkers: [
            { id: "zom_chart_showcase_top", start: 1.4, duration: 2.2, focus: { x: 960, y: 330 }, scale: 1.25 },
            { id: "zom_chart_showcase_bottom", start: 6.2, duration: 2.6, focus: { x: 960, y: 880 }, scale: 1.3 },
          ],
          translationMarkers: [],
          objects: [
            {
              id: "chart-showcase-title",
              name: "Chart Showcase Title",
              type: "text",
              selector: "[data-object-id='chart-showcase-title']",
              bounds: { x: 92, y: 52, width: 1050, height: 72 },
              content: "Built-in chart templates",
              style: { color: "#ffffff", fontSize: 56, fontWeight: 820, letterSpacing: -2.2, lineHeight: 1 },
              motion: { y: [24, 0], opacity: [0, 1], duration: 0.7, ease: "easeOut" },
            },
            {
              id: "chart-showcase-subtitle",
              name: "Chart Showcase Subtitle",
              type: "text",
              selector: "[data-object-id='chart-showcase-subtitle']",
              bounds: { x: 96, y: 122, width: 1080, height: 42 },
              content: "Open Code mode: this template showcases line, area, bar, grouped, stacked, bubble, donut, radar, gauge, heatmap, waterfall, and radial charts.",
              style: { color: "rgba(218,233,246,0.66)", fontSize: 23, fontWeight: 520, letterSpacing: -0.2 },
              motion: { y: [16, 0], opacity: [0, 1], duration: 0.65, delay: 0.16, ease: "easeOut" },
            },
          ],
        },
        {
          id: "prt_editor_surface",
          name: "Editor Surface",
          filePath: "clipper/projects/prj_v01_sample/scn_opening/prt_editor_surface.ts",
          duration: 8,
          frame: { width: 1920, height: 1080, style: { background: "#050505" } },
          background: { id: "background", name: "Background", style: { background: "#050505" }, elements: [] },
          snapshot: [
            { at: "00:02", description: "The shared hero-title id pans into an editor annotation." },
            { at: "00:05", description: "Inspector and screenshot selector metadata are emphasized." },
            { at: "00:08", description: "Ending with zoom row and main timeline aligned." },
          ],
          zoomMarkers: [
            { id: "zom_inspector", start: 3.4, duration: 2.8, focus: { x: 1540, y: 430 }, scale: 1.8 },
          ],
          translationMarkers: [],
          objects: [
            {
              id: "hero-title",
              name: "Hero Title Continuity",
              type: "text",
              selector: "[data-object-id='hero-title']",
              bounds: { x: 120, y: 130, width: 650, height: 110 },
              content: "Shared IDs unlock hero pans",
              style: { color: "#ffffff", fontSize: 48, fontWeight: 720, letterSpacing: -1.5 },
              layoutId: "hero-title",
              motion: { opacity: [0, 1], duration: 0.7, ease: "easeInOut" },
            },
            {
              id: "inspector-card",
              name: "Inspector Card",
              type: "rect",
              selector: "[data-object-id='inspector-card']",
              bounds: { x: 1290, y: 210, width: 420, height: 520 },
              style: { background: "#111820", border: "2px solid var(--clipper-accent)", borderRadius: 26 },
              motion: { opacity: [0, 1], x: [60, 0], duration: 0.6, ease: "easeOut" },
            },
            {
              id: "selector-box-demo",
              name: "Screenshot Selector Demo",
              type: "rect",
              selector: "[data-object-id='selector-box-demo']",
              bounds: { x: 350, y: 430, width: 690, height: 330 },
              style: { background: "rgb(var(--clipper-accent-rgb) / 0.12)", border: "3px dashed var(--clipper-accent)", borderRadius: 8 },
              motion: { opacity: [0, 1], duration: 1, ease: "linear" },
            },
          ],
        },
      ],
    },
  ],
};
